## NumPy 라이브러리 불러오기





In [ ]:
import numpy as np
print(np.__version__)

1.22.4


In [ ]:
import numpy
print(numpy.__version__)

1.22.4


## 리스트를 배열로 변환
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html

In [ ]:
temp = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] # 리스트는 사칙연산 불가
temp_array = np.array(temp)
print(temp)
print(temp_array) # 배열은 쉼표가 없다

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(type(temp))
print(type(temp_array))
print(temp_array.shape)
print(temp_array.ndim)

<class 'list'>
<class 'numpy.ndarray'>
(10,)
1


- 첫번째 인수를 출력

In [ ]:
temp_array[1]

2

In [ ]:
temp_array[-1]

10

- 사칙연산(리스트를 배열로 바꿔서)

In [ ]:
score1 = [10, 15, 40, 50, 80]
score2 = [30, 40, 70, 50, 100]

score1 + score2  # 서로 더한 값이 안나오고 연결된 상태로 출력됨

[10, 15, 40, 50, 80, 30, 40, 70, 50, 100]

In [ ]:
score1_arr = np.array(score1)
score2_arr = np.array(score2)

result = score1_arr + score2_arr
print(result)

[ 40  55 110 100 180]


In [ ]:
np.min(result)

40

In [ ]:
np.max(result)

180

In [ ]:
np.sum(result)

485

## 배열(행렬)의 생성
- 0차원부터 3차원까지로 구성

In [ ]:
temp_arr = np.array(30)
print(temp_arr)
print(type(temp_arr))
print(temp_arr.shape)

30
<class 'numpy.ndarray'>
()


In [ ]:
temp_arr = np.array([1, 2, 3])
print(temp_arr.shape)
print(temp_arr.ndim)

(3,)
1


## 2차원
- 정형 데이터(엑셀 데이터)

In [ ]:
temp_arr = np.array([[1, 2, 3],[4, 5, 6]])
print(temp_arr.shape)
print(temp_arr.ndim)

(2, 3)
2


## 3차원
- 이미지 데이터

In [ ]:
temp_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(temp_arr.shape)
print(temp_arr.ndim)

(2, 2, 3)
3


In [ ]:
temp_arr = np.array([1, 2, 3, 4], ndmin=3)
print(temp_arr.shape)
print(temp_arr.ndim)

(1, 1, 4)
3


## 배열 생성의 다양한 방법들
- 모두 0으로 채운

In [ ]:
temp_arr = np.zeros((5, 10))
temp_arr .dtype

dtype('float64')

- 모두 1로 채운다

In [ ]:
temp_arr = np.ones((5, 10))
temp_arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

- 임의의 상수값으로 채운다

In [ ]:
temp_arr = np.full((2,3), 10)
temp_arr

array([[10, 10, 10],
       [10, 10, 10]])

- 최소 및 최대 숫자의 범위를 정해두고, 구간별로 값을 생성하는 코드를 작성함


In [ ]:
temp_arr = np.linspace(5, 10, 5)
temp_arr

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

- np.arange()

In [ ]:
temp_arr = np.arange(1, 100, 4)
temp_arr

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

- 임의의 난수 생성

In [ ]:
from numpy import random
x  = random.rand()
print(x)

0.4265644682453702


In [ ]:
import numpy as np
x = np.random.rand()
print(x)

0.10940735934207513


In [ ]:
from numpy.random import rand
x = rand()
print(x)

0.3332730936517696


## 배열 연산
- 덧셈 : np.add()
- 뺄셈 : np.subtract()
- 곱셈 : np.multiply()
- 나눗셈 : np.divide()

In [ ]:
import numpy as np

array_01 =np.array([1, 2, 3])
array_02 = np.array([10, 20, 30])

# 덧셈
result = np.add(array_01, array_02)
result

array([11, 22, 33])

In [ ]:
# 뺄셈
result = np.subtract(array_01, array_02)
result

array([ -9, -18, -27])

In [ ]:
# 곱셈
result = np.multiply(array_01, array_02)
result

array([1, 4, 9])

In [ ]:
# 나눗셈
result = np.divide(array_01, array_02)
result

array([0.1, 0.1, 0.1])

In [ ]:
array_01 =np.array([1, 2, 3])
array_02 =np.array([1, 2, 3])

result = np.power(array_01, array_02)
print(result)

[ 1  4 27]


## 소숫점 정렬
- 소숫점 절삭

- 코드는 실행속도 체크

In [ ]:
%%time

temp_arr = np.trunc([-1.23, 1.23])
print(temp_arr)

[-1.  1.]
CPU times: user 1.13 ms, sys: 6 µs, total: 1.13 ms
Wall time: 1.15 ms


In [ ]:
%%time

temp_arr = np.fix([-1.23, 1.23])
print(temp_arr)

[-1.  1.]
CPU times: user 1.39 ms, sys: 0 ns, total: 1.39 ms
Wall time: 1.4 ms


- 소숫점 자리에서 반올림

In [ ]:
temp_arr = np.around([-1.123131, 1.123131] , 3)
print(temp_arr)

temp_arr = np.round([-1.123131, 1.123131] , 3)
print(temp_arr)


[-1.123  1.123]
[-1.123  1.123]


- 소숫점 모두 내린다

In [ ]:
import time

#Start time
start_time = time.time()

temp_arr = np.floor([-1.123131, 1.123131])
print(temp_arr)

# End time
end_time = time.time()

# Execution time
execution_time = end_time - start_time

print("Execution time:" , execution_time)

[-2.  1.]
Execution time: 0.0024423599243164062


## 조건문
- where : 조건식 1개일 때 활용
- select : 다중조건일 때 활용

In [ ]:
temp_arr = np.arange(10)
temp_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- np.where

In [ ]:
np.where(temp_arr < 5, temp_arr, 10 * temp_arr)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [ ]:
temp_srr = np.arange(10)
cond_list = [temp_arr > 5, temp_arr < 2]
choice_list = [temp_arr * 3, temp_arr +10]

np.select(cond_list, choice_list, default = temp_arr)

array([10, 11,  2,  3,  4,  5, 18, 21, 24, 27])

- **브로드캐스팅**은 서로 다른 크기의 배열을 계산할 때의 기본적인 규칙을 의미한다

- 참조 : https://numpy.org/devdocs/user/basics.broadcasting.html